services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    expose:
      - 5432
  node_app:
    container_name: node_app
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
    command: "npm run start"
